spring:
  application:
    name: sigdep-console-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/sigdep}
    username: ${SPRING_DATASOURCE_USERNAME:sigdep}
    password: ${SPRING_DATASOURCE_PASSWORD:sigdep}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: core
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/sigdep}
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8081
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
